package com.yubai.blog.post;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

import com.yubai.blog.TestDatabase;
import java.sql.DriverManager;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class PostWorkflowSchedulingIntegrationTest {
    private static final String SCHEMA = "post_schedule_claim_test";
    private static final Instant NOW = Instant.parse("2027-01-15T08:00:00Z");
    private static JdbcTemplate jdbc;

    @BeforeAll
    static void setUpDatabase() throws Exception {
        try (var connection =
                        DriverManager.getConnection(
                                TestDatabase.URL, TestDatabase.USERNAME, TestDatabase.PASSWORD);
                var statement = connection.createStatement()) {
            statement.execute("drop schema if exists " + SCHEMA + " cascade");
            statement.execute("create schema " + SCHEMA);
        }
        var separator = TestDatabase.URL.contains("?") ? "&" : "?";
        var dataSource =
                new DriverManagerDataSource(
                        TestDatabase.URL + separator + "currentSchema=" + SCHEMA,
                        TestDatabase.USERNAME,
                        TestDatabase.PASSWORD);
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute(
                """
                create table posts (
                    id bigint primary key,
                    status varchar(20) not null,
                    scheduled_publish_at timestamptz
                );
                create table post_publication_audit (
                    id bigint generated by default as identity primary key,
                    post_id bigint,
                    action varchar(30) not null,
                    actor varchar(120) not null,
                    detail text,
                    created_at timestamptz not null default now()
                )
                """);
    }

    @AfterAll
    static void cleanUpDatabase() throws Exception {
        try (var connection =
                        DriverManager.getConnection(
                                TestDatabase.URL, TestDatabase.USERNAME, TestDatabase.PASSWORD);
                var statement = connection.createStatement()) {
            statement.execute("drop schema if exists " + SCHEMA + " cascade");
        }
    }

    @Test
    void concurrentAndRepeatedScansPublishAndAuditExactlyOnce() throws Exception {
        jdbc.update(
                "insert into posts (id, status, scheduled_publish_at) values (1, 'DRAFT', ?)",
                java.sql.Timestamp.from(NOW.minusSeconds(1)));
        var serviceA = service();
        var serviceB = service();
        var start = new CountDownLatch(1);

        try (var workers = Executors.newFixedThreadPool(2)) {
            var first = workers.submit(() -> runAfter(start, serviceA));
            var second = workers.submit(() -> runAfter(start, serviceB));
            start.countDown();

            assertThat(first.get().size() + second.get().size()).isEqualTo(1);
        }

        assertThat(serviceA.publishDueAt(NOW)).isEmpty();
        assertThat(jdbc.queryForObject("select status from posts where id = 1", String.class))
                .isEqualTo("PUBLISHED");
        assertThat(
                        jdbc.queryForObject(
                                "select count(*) from post_publication_audit where post_id = 1 and action = 'SCHEDULED_PUBLISH'",
                                Long.class))
                .isEqualTo(1L);
    }

    private static java.util.List<Long> runAfter(CountDownLatch start, PostWorkflowService service)
            throws InterruptedException {
        start.await();
        return service.publishDueAt(NOW);
    }

    private static PostWorkflowService service() {
        return new PostWorkflowService(
                mock(PostRepository.class), jdbc, Clock.fixed(NOW, ZoneOffset.UTC));
    }
}
