create table series (
    id bigint generated by default as identity primary key,
    name varchar(200) not null,
    slug varchar(200) not null unique,
    description text not null default '',
    cover_image varchar(500),
    status varchar(20) not null default 'DRAFT',
    version bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    published_at timestamp with time zone
);

create table series_entries (
    id bigint generated by default as identity primary key,
    series_id bigint not null references series(id) on delete cascade,
    content_type varchar(20) not null,
    content_id bigint not null,
    sort_order integer not null default 0,
    chapter_title varchar(200),

    unique (series_id, content_type, content_id)
);

create index series_entries_series_idx on series_entries (series_id);
create index series_entries_content_idx on series_entries (content_type, content_id);
create index series_status_idx on series (status);
create index series_published_at_idx on series (published_at desc);
