create table music_tracks (
    id bigint generated by default as identity primary key,
    track_id varchar(60) not null unique,
    title varchar(200) not null,
    artist varchar(120) not null,
    duration integer not null check (duration > 0),
    audio_url text not null,
    cover_url text not null,
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

create index music_tracks_sort_order_idx on music_tracks (sort_order asc, id asc);

insert into music_tracks (track_id, title, artist, duration, audio_url, cover_url, sort_order) values
('track-1', '雨的印记 (Kiss the Rain)', '钢琴纯音乐', 220,
 'https://cdn.example.com/music/kiss-the-rain.mp3',
 'https://cdn.example.com/music/covers/rain.jpg', 1),
('track-2', '安妮的仙境 (Annie''s Wonderland)', '舒缓吉他与长笛', 240,
 'https://cdn.example.com/music/annies-wonderland.mp3',
 'https://cdn.example.com/music/covers/wonderland.jpg', 2),
('track-3', '静谧森林 (Forest Acoustic)', '自然轻音乐', 210,
 'https://cdn.example.com/music/forest-acoustic.mp3',
 'https://cdn.example.com/music/covers/forest.jpg', 3),
('track-4', '月光边境 (Moonlight Frontier)', '钢琴与弦乐', 260,
 'https://cdn.example.com/music/moonlight-frontier.mp3',
 'https://cdn.example.com/music/covers/moonlight.jpg', 4),
('track-5', '清晨 (Morning Air)', '陶笛与钢琴', 200,
 'https://cdn.example.com/music/morning-air.mp3',
 'https://cdn.example.com/music/covers/morning.jpg', 5);
