create table sys_quote (
    id bigint generated by default as identity primary key,
    content text not null,
    author varchar(120) not null default '',
    category varchar(80) not null default '',
    display_order integer not null default 0,
    created_at timestamptz not null default now()
);

create index sys_quote_display_order_idx on sys_quote (display_order asc, id asc);

insert into sys_quote (content, author, category, display_order) values
('代码是写给人看的，只是顺便让机器能够运行。', '《SICP》', '极客哲学', 1),
('留白，不是空无，而是给灵感与思考呼吸的空间。', '余白手记', '设计美学', 2),
('简单比复杂更难：你必须付出巨大努力，才能让一切变得简单。', 'Steve Jobs', '极客哲学', 3),
('好的设计就是尽可能少的设计。', 'Dieter Rams', '设计美学', 4),
('不要因为走得远，而忘记了为什么出发。', '《LIFE》', '生活感悟', 5),
('每一天都是一次新的开始，抓住它。', '余白手记', '生活感悟', 6);
