-- 4A-1：AI 供应商注册表（密钥 AES-GCM 加密存储）；ai_usage 用量审计表同批建立，由 4A-6 开始写入。
create table ai_providers (
    id bigint generated by default as identity primary key,
    name varchar(60) not null unique,
    base_url text not null,
    api_key_encrypted text,
    models text not null default '',
    default_model varchar(120) not null,
    enabled boolean not null default true,
    is_default boolean not null default false,
    daily_request_limit integer not null default 200 check (daily_request_limit > 0),
    daily_token_limit integer not null default 200000 check (daily_token_limit > 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table ai_usage (
    id bigint generated by default as identity primary key,
    provider_id bigint not null references ai_providers(id) on delete cascade,
    model varchar(120) not null,
    prompt_tokens integer not null default 0,
    completion_tokens integer not null default 0,
    latency_ms integer not null default 0,
    status varchar(20) not null,
    created_at timestamptz not null default now()
);

create index ai_usage_provider_created_idx on ai_usage (provider_id, created_at);
