-- FD-10/FD-15（美食专项 D2 ①③）：预定今日菜单（两人协作编排）与吃饭打卡·美食时光机。
-- 台账注：规划号 V18 被 pg_trgm（并行会话）先落盘占用，本迁移顺延 V19（见 e92a43c 台账修正）。
--
-- 隐私边界：三张表全是两人私有数据（含作息与留言），端点一律挂 /api/v1/kitchen/**。
-- ⚠️ 绝不可挂 /api/v1/dishes/** 之下——该前缀在 SecurityConfiguration 中是
--    GET permitAll 的 Ant 前缀匹配，且被 WebConfiguration 加 5 分钟 public 缓存，
--    挂错等于把生活轨迹公网可读且滞后 5 分钟。

create table daily_menus (
    id          bigint       generated by default as identity primary key,
    menu_date   date         not null unique,
    status      varchar(20)  not null default 'DRAFT'
                             check (status in ('DRAFT', 'CONFIRMED')),
    note        varchar(500) not null default '',   -- 与 DailyMenuRequest.@Size(max=500) 同步
    created_by  bigint       not null references admin_users(id),
    updated_by  bigint       not null references admin_users(id),
    -- 乐观锁：Service 的全量 PUT 必须经 OPTIMISTIC_FORCE_INCREMENT 加锁读取，
    -- 否则"只改子表"时 JPA 不会标脏父实体，version 永不变、409 永不触发。
    version     bigint       not null default 0,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now()
);
create index daily_menus_date_desc_idx on daily_menus (menu_date desc);

create table daily_menu_items (
    id          bigint       generated by default as identity primary key,
    menu_id     bigint       not null references daily_menus(id) on delete cascade,
    -- 可空：想吃的菜可能还没进菜谱库；菜谱被删后（set null）历史菜单仍完整
    dish_id     bigint       references dishes(id) on delete set null,
    -- 写入时快照 dish.name；菜谱改名/删除不影响历史菜单
    title       varchar(120) not null,
    meal_slot   varchar(16)  not null default 'DINNER'
                             check (meal_slot in ('BREAKFAST','LUNCH','DINNER','SNACK')),
    note        varchar(200) not null default '',
    -- 故意用普通列而非 unique：全量重排会出现中间态冲突，自洽由服务端按数组下标重算保证
    sort_order  integer      not null default 0,
    -- 鉴权与署名只看 author_id；author_name 是快照，用户名/展示名变更后历史署名仍保真。
    -- ⚠️ 全量 PUT 必须按 item.id 做 diff，不得 delete-all+insert-all，否则这两列被改写。
    author_id   bigint       not null references admin_users(id),
    author_name varchar(40)  not null,
    created_at  timestamptz  not null default now()
);
create index daily_menu_items_menu_idx on daily_menu_items (menu_id, meal_slot, sort_order, id);
create index daily_menu_items_dish_idx on daily_menu_items (dish_id);

create table meal_logs (
    id          bigint       generated by default as identity primary key,
    -- 实际吃的日期（可事后补记），不等于 created_at
    log_date    date         not null,
    dish_id     bigint       references dishes(id) on delete set null,
    title       varchar(120) not null,
    meal_slot   varchar(16)  not null default 'DINNER'
                             check (meal_slot in ('BREAKFAST','LUNCH','DINNER','SNACK')),
    -- 这一次做得怎么样；与 dishes.rating（后台手填的静态展示分）语义正交
    rating      integer      check (rating between 1 and 5),
    note        varchar(300) not null default '',
    author_id   bigint       not null references admin_users(id),
    author_name varchar(40)  not null,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now()
);
create index meal_logs_timeline_idx on meal_logs (log_date desc, id desc);
-- 「做过 N 次 / 上次什么时候」聚合：GROUP BY dish_id + MAX(log_date) 全走此索引；
-- 刻意不在 dishes 上加冗余计数列（删除后仍要回查聚合，冗余只省一半）
create index meal_logs_dish_idx on meal_logs (dish_id, log_date desc);

-- 无 seed：菜单/打卡是两人产生的真实内容，假数据会污染时间线。
-- meal_logs 的实体与端点由 FD-15 落地（ddl-auto=validate 只校验已映射实体，先建表无害）。
