create table posts (
    id bigint generated by default as identity primary key,
    slug varchar(120) not null unique,
    title varchar(200) not null,
    excerpt text not null,
    published_date date not null,
    read_time integer not null check (read_time > 0),
    category varchar(80) not null,
    color varchar(20) not null,
    display_number varchar(10) not null,
    featured boolean not null default false,
    content text not null
);

create table post_tags (
    post_id bigint not null references posts(id) on delete cascade,
    tag varchar(80) not null,
    sort_order integer not null,
    primary key (post_id, sort_order)
);

create table projects (
    id bigint generated by default as identity primary key,
    title varchar(160) not null,
    description text not null,
    year varchar(10) not null,
    status varchar(40) not null,
    color varchar(20) not null,
    display_order integer not null
);

create table project_stack (
    project_id bigint not null references projects(id) on delete cascade,
    technology varchar(80) not null,
    sort_order integer not null,
    primary key (project_id, sort_order)
);

create index posts_published_date_idx on posts (published_date desc);
create index posts_category_idx on posts (category);
create index projects_display_order_idx on projects (display_order);

insert into posts (slug, title, excerpt, published_date, read_time, category, color, display_number, featured, content) values
('clarity-by-design', '把复杂留给系统，把清晰留给读者', '一个好界面并不展示所有能力，而是在每个决定发生的时刻，只给出恰到好处的信息。', '2026-07-18', 8, '设计札记', '#1649d8', '01', true, $body$
<p class="lead">复杂从来不会真正消失。好的设计，只是把它安放到了更合适的位置。</p>
<h2 id="start">清晰不是删减，而是排序</h2>
<p>每一个成熟的产品背后，都存在大量状态、规则和边界条件。面向读者时，我们要做的不是假装这些复杂性不存在，而是建立一条清楚的阅读路径：先看见结论，再理解依据，最后保留深入探索的入口。</p>
<blockquote>信息不是越多越好。真正稀缺的是读者的注意力，以及我们替他们完成排序的能力。</blockquote>
<h2 id="rhythm">让界面拥有阅读节奏</h2>
<p>字号、留白、颜色和动效共同决定了页面的语气。稳定的间距系统能让内容自然分组，有限的强调色能建立优先级，而克制的动效负责解释状态变化。</p>
<pre><code>const clarity = complexity
  .sort(byRelevance)
  .map(toHumanLanguage)
  .filter(keepWhatMatters)</code></pre>
<h2 id="system">设计系统应该服务内容</h2>
<p>组件库不是一面展示墙。它的价值在于让团队能够持续地做出一致决定，同时给重要内容留下打破规则的空间。</p>
<ul><li>先定义内容层级，再选择组件。</li><li>用有限的视觉变量表达明确的语义。</li><li>让每一种交互都有可预期的反馈。</li></ul>
<p>当系统承担了复杂性，读者得到的便不是“简单”，而是一种被认真照顾过的清晰。</p>
$body$),
('vue-composable-notes', 'Vue Composable 的边界感', '从“复用几行代码”到“描述一个稳定的领域能力”，组合式函数真正值得抽象的时机。', '2026-07-12', 6, '工程实践', '#ff6b35', '02', false, $body$<p class="lead">抽象的目标不是减少文件，而是让变化发生在正确的位置。</p><h2 id="signal">先寻找稳定信号</h2><p>当一段逻辑跨越多个组件，并且拥有清楚的输入、输出与生命周期，它才开始具备成为 composable 的条件。</p><h2 id="contract">用类型写下契约</h2><p>TypeScript 让边界变得可见：参数表达依赖，返回值表达能力，而命名表达意图。</p><pre><code>export function useReadingList(storage: Storage) {
  const items = ref&lt;string[]&gt;([])
  const toggle = (slug: string) =&gt; { /* ... */ }
  return { items: readonly(items), toggle }
}</code></pre><p>最好的组合式函数通常很无聊：行为稳定、依赖明确、无需阅读实现就能正确使用。</p>$body$),
('slow-interface', '慢一点的界面，反而更有力量', '当所有产品都在争抢注意力，克制、停顿与空白如何变成一种更长久的体验。', '2026-07-03', 5, '日常观察', '#d7ef63', '03', false, $body$<p class="lead">速度是一种能力，但从来不是体验的唯一尺度。</p><h2 id="pause">允许停顿发生</h2><p>一个页面不必在首屏解释一切。空白可以建立期待，过渡可以帮助理解，适当的延迟甚至能让动作显得更有重量。</p><blockquote>克制不是缺少表达，而是知道什么值得被放大。</blockquote><h2 id="quiet">安静的产品</h2><p>关闭不必要的通知、减少竞争性的按钮、把阅读进度交还给用户。安静不是消极，它是一种对注意力的尊重。</p>$body$),
('type-safe-content', '用 TypeScript 管好一座内容花园', '静态内容也值得拥有可靠的结构：从文章元数据到路由，再到可维护的展示逻辑。', '2026-06-21', 7, '工程实践', '#8c7bff', '04', false, $body$<p class="lead">内容与代码的边界越清楚，网站就越容易继续生长。</p><h2 id="model">先建立内容模型</h2><p>标题、摘要、日期、标签与正文不仅是字段，更是页面能力的来源。可靠的模型能驱动筛选、推荐与 SEO。</p><h2 id="future">为未来留接口</h2><p>今天的数据来自本地文件，明天也可以替换成 Markdown 或 CMS，而展示层无需推倒重来。</p>$body$),
('weekend-camera', '周末散步的 24 个画面', '不追求目的地，只记录光线、转角和城市里那些短暂却具体的时刻。', '2026-06-08', 4, '日常观察', '#f2c94c', '05', false, $body$<p class="lead">散步是一种低速的搜索方式。</p><h2 id="light">下午四点的光</h2><p>阳光沿着旧楼的边缘落下，橱窗、树影和路人的衣角暂时拥有同一种颜色。</p><h2 id="collect">收集而不占有</h2><p>按下快门不是为了证明到过，而是提醒自己：平常的一天也有值得认真观看的部分。</p>$body$);

insert into post_tags (post_id, tag, sort_order)
select id, '产品设计', 0 from posts where slug = 'clarity-by-design'
union all select id, '信息架构', 1 from posts where slug = 'clarity-by-design'
union all select id, 'Vue', 0 from posts where slug = 'vue-composable-notes'
union all select id, 'TypeScript', 1 from posts where slug = 'vue-composable-notes'
union all select id, '体验', 0 from posts where slug = 'slow-interface'
union all select id, '生活', 1 from posts where slug = 'slow-interface'
union all select id, 'TypeScript', 0 from posts where slug = 'type-safe-content'
union all select id, '内容系统', 1 from posts where slug = 'type-safe-content'
union all select id, '摄影', 0 from posts where slug = 'weekend-camera'
union all select id, '城市', 1 from posts where slug = 'weekend-camera';

insert into projects (title, description, year, status, color, display_order) values
('Mori 阅读器', '一款强调专注与批注关系的长文阅读原型。', '2026', '进行中', '#1649d8', 1),
('Tiny Metrics', '为独立创作者设计的轻量、隐私友好数据看板。', '2025', '已发布', '#ff6b35', 2),
('微光计划', '收集日常微小灵感的离线优先网页应用。', '2025', '实验', '#d7ef63', 3);

insert into project_stack (project_id, technology, sort_order)
select id, 'Vue 3', 0 from projects where title = 'Mori 阅读器'
union all select id, 'TypeScript', 1 from projects where title = 'Mori 阅读器'
union all select id, 'IndexedDB', 2 from projects where title = 'Mori 阅读器'
union all select id, 'Vite', 0 from projects where title = 'Tiny Metrics'
union all select id, 'ECharts', 1 from projects where title = 'Tiny Metrics'
union all select id, 'Cloudflare', 2 from projects where title = 'Tiny Metrics'
union all select id, 'PWA', 0 from projects where title = '微光计划'
union all select id, 'Vue', 1 from projects where title = '微光计划'
union all select id, 'CSS', 2 from projects where title = '微光计划';
