-- 4C：文章草稿版本历史——每次管理端保存快照一份正文相关字段，按篇保留最近 10 版
create table post_revisions (
    id bigint generated by default as identity primary key,
    post_id bigint not null references posts(id) on delete cascade,
    title varchar(200) not null,
    excerpt text not null default '',
    content text not null default '',
    markdown_content text,
    content_format varchar(16) not null default 'HTML',
    created_at timestamp with time zone not null
);

create index post_revisions_post_idx on post_revisions (post_id, created_at desc, id desc);
