create table admin_users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    password_hash varchar(100) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);
