create table post_categories (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    slug varchar(255) not null,
    description varchar(500) not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint post_categories_name_unique unique (name),
    constraint post_categories_slug_unique unique (slug),
    constraint post_categories_name_not_blank check (btrim(name) <> ''),
    constraint post_categories_slug_not_blank check (btrim(slug) <> '')
);

insert into post_categories (name, slug)
select distinct on (lower(btrim(category))) btrim(category), category_slug
from posts
order by lower(btrim(category)), id;
