create table dish_categories (
    id bigint generated by default as identity primary key,
    name varchar(60) not null unique,
    slug varchar(255) not null unique,
    description varchar(500) not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint dish_categories_name_not_blank check (btrim(name) <> ''),
    constraint dish_categories_slug_not_blank check (btrim(slug) <> '')
);

insert into dish_categories (name, slug)
select distinct on (lower(btrim(category))) btrim(category), lower(btrim(category))
from dishes
order by lower(btrim(category)), id;
