create table learning_notes (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    markdown_content text not null,
    folder varchar(100) not null default '未分类',
    status varchar(20) not null default 'DRAFT',
    source_file_name varchar(255),
    word_count integer not null default 0,
    version bigint not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint learning_notes_status_check check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

create table learning_note_tags (
    note_id bigint not null references learning_notes(id) on delete cascade,
    tag varchar(80) not null,
    sort_order integer not null,
    primary key (note_id, sort_order)
);

create index learning_notes_updated_at_idx on learning_notes(updated_at desc);
create index learning_notes_status_idx on learning_notes(status);
