create table note_attachments (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    note_id bigint not null references learning_notes(id) on delete cascade,
    file_name varchar(255) not null,
    media_type varchar(100) not null,
    byte_size bigint not null,
    content bytea not null,
    created_at timestamp with time zone not null default now()
);

create index note_attachments_note_id_idx on note_attachments(note_id);
