alter table posts add column scheduled_publish_at timestamptz;

create index idx_posts_scheduled_publish
    on posts (scheduled_publish_at)
    where status = 'DRAFT' and scheduled_publish_at is not null;

create table post_publication_audit (
    id bigint generated by default as identity primary key,
    post_id bigint references posts(id) on delete set null,
    action varchar(30) not null,
    actor varchar(120) not null,
    detail text,
    created_at timestamptz not null default now()
);

create index idx_post_publication_audit_created_at
    on post_publication_audit (created_at desc);
