create table dishes (
    id bigint generated by default as identity primary key,
    slug varchar(120) not null unique,
    name varchar(120) not null,
    summary text not null,
    category varchar(60) not null,
    image_url text not null,
    image_alt varchar(240) not null,
    image_credit varchar(240) not null,
    image_source_url text not null,
    prep_minutes integer not null check (prep_minutes > 0),
    difficulty varchar(20) not null check (difficulty in ('简单', '家常', '进阶')),
    rating numeric(2, 1) not null check (rating between 0 and 5),
    featured boolean not null default false,
    published boolean not null default true,
    display_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table dish_ingredients (
    dish_id bigint not null references dishes(id) on delete cascade,
    ingredient varchar(240) not null,
    sort_order integer not null,
    primary key (dish_id, sort_order)
);

create table dish_steps (
    dish_id bigint not null references dishes(id) on delete cascade,
    instruction text not null,
    sort_order integer not null,
    primary key (dish_id, sort_order)
);

create index dishes_public_order_idx on dishes (published, featured desc, display_order asc);
create index dishes_category_idx on dishes (category);

insert into dishes (
    slug, name, summary, category, image_url, image_alt, image_credit, image_source_url,
    prep_minutes, difficulty, rating, featured, published, display_order
) values
(
    'authentic-mapo-tofu', '麻婆豆腐', '豆腐吸满红亮汤汁，花椒的麻与豆瓣的香在热气里慢慢展开。', '川味经典',
    '/food/mapo-tofu.jpg', '盛在白色浅碗中的四川麻婆豆腐，表面有肉末、辣油和葱花',
    'Sichuanfoodlover · CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Authentic_Mapo_Tofu.jpg',
    28, '家常', 4.9, true, true, 1
),
(
    'kung-pao-chicken', '宫保鸡丁', '鸡丁、花生与干辣椒在大火中快速交汇，酸甜之后留下一点椒麻。', '川味经典',
    '/food/kung-pao-chicken.jpg', '盘中的宫保鸡丁，包含鸡肉、花生、干辣椒和青葱',
    'princeroy · CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Kungpao_chicken.jpg',
    25, '家常', 4.8, false, true, 2
),
(
    'dongpo-pork', '东坡肉', '用时间换来的软糯口感，酱油、冰糖与香料收成温润浓厚的光泽。', '周末料理',
    'https://commons.wikimedia.org/wiki/Special:Redirect/file/Dongpo_pork_garnished.jpg?width=1600',
    '深色陶碗中以青菜点缀的东坡肉，肉块酱色红亮',
    'CNEcija12345 · CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Dongpo_pork_garnished.jpg',
    95, '进阶', 4.9, true, true, 3
),
(
    'handmade-jiaozi', '手工水饺', '从和面、调馅到捏合，每一只饺子都保留手作的不完全一致。', '面点主食',
    'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chinese_dumplings_(Jiaozi)_(2196005904).jpg?width=1600',
    '白色盘中整齐摆放的中国手工水饺',
    'David Pursehouse · CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Chinese_dumplings_(Jiaozi)_(2196005904).jpg',
    70, '进阶', 4.7, false, true, 4
),
(
    'garlic-broccoli', '蒜香西兰花', '脆嫩西兰花只用蒜与盐提味，是十分钟就能端上桌的清爽一盘。', '十分钟菜',
    'https://commons.wikimedia.org/wiki/Special:Redirect/file/Stir-fried_broccoli.jpg?width=1600',
    '白盘中的清炒西兰花，颜色翠绿并带有蒜粒',
    'Fumikas Sagisavas · CC0', 'https://commons.wikimedia.org/wiki/File:Stir-fried_broccoli.jpg',
    12, '简单', 4.5, false, true, 5
),
(
    'sweet-sour-pork', '菠萝咕咾肉', '酥脆肉块裹上酸甜亮汁，与菠萝和青椒组成明快的粤式味道。', '粤式家常',
    'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sweet_and_Sour_Pork.jpg?width=1600',
    '白盘中的菠萝咕咾肉，包含炸猪肉、彩椒和酸甜酱汁',
    'Neodymium+Nd · CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Sweet_and_Sour_Pork.jpg',
    40, '家常', 4.6, false, true, 6
);

insert into dish_ingredients (dish_id, ingredient, sort_order)
select id, '嫩豆腐 400 克', 0 from dishes where slug = 'authentic-mapo-tofu'
union all select id, '牛肉末 80 克', 1 from dishes where slug = 'authentic-mapo-tofu'
union all select id, '郫县豆瓣酱 1 汤匙', 2 from dishes where slug = 'authentic-mapo-tofu'
union all select id, '花椒粉、蒜苗与水淀粉适量', 3 from dishes where slug = 'authentic-mapo-tofu'
union all select id, '鸡腿肉 300 克', 0 from dishes where slug = 'kung-pao-chicken'
union all select id, '熟花生 60 克', 1 from dishes where slug = 'kung-pao-chicken'
union all select id, '干辣椒、花椒与大葱适量', 2 from dishes where slug = 'kung-pao-chicken'
union all select id, '生抽、香醋、糖与淀粉适量', 3 from dishes where slug = 'kung-pao-chicken'
union all select id, '带皮五花肉 600 克', 0 from dishes where slug = 'dongpo-pork'
union all select id, '绍兴黄酒 350 毫升', 1 from dishes where slug = 'dongpo-pork'
union all select id, '生抽 60 毫升、老抽 15 毫升', 2 from dishes where slug = 'dongpo-pork'
union all select id, '冰糖 45 克、葱姜适量', 3 from dishes where slug = 'dongpo-pork'
union all select id, '中筋面粉 400 克', 0 from dishes where slug = 'handmade-jiaozi'
union all select id, '猪肉馅 300 克', 1 from dishes where slug = 'handmade-jiaozi'
union all select id, '大白菜 350 克', 2 from dishes where slug = 'handmade-jiaozi'
union all select id, '葱姜水、生抽与香油适量', 3 from dishes where slug = 'handmade-jiaozi'
union all select id, '西兰花 1 颗', 0 from dishes where slug = 'garlic-broccoli'
union all select id, '大蒜 4 瓣', 1 from dishes where slug = 'garlic-broccoli'
union all select id, '盐与食用油适量', 2 from dishes where slug = 'garlic-broccoli'
union all select id, '猪里脊 350 克', 0 from dishes where slug = 'sweet-sour-pork'
union all select id, '菠萝 150 克', 1 from dishes where slug = 'sweet-sour-pork'
union all select id, '青红甜椒各半个', 2 from dishes where slug = 'sweet-sour-pork'
union all select id, '番茄酱、白醋、糖与淀粉适量', 3 from dishes where slug = 'sweet-sour-pork';

insert into dish_steps (dish_id, instruction, sort_order)
select id, '豆腐切方块，用淡盐水小火焯一分钟后沥干。', 0 from dishes where slug = 'authentic-mapo-tofu'
union all select id, '炒香牛肉末与豆瓣酱，加入蒜末和适量高汤。', 1 from dishes where slug = 'authentic-mapo-tofu'
union all select id, '放入豆腐轻推入味，分次勾芡，出锅撒花椒粉与蒜苗。', 2 from dishes where slug = 'authentic-mapo-tofu'
union all select id, '鸡肉切丁，用盐、料酒与淀粉抓匀腌制十分钟。', 0 from dishes where slug = 'kung-pao-chicken'
union all select id, '调匀生抽、香醋、糖、淀粉与少量清水作为碗汁。', 1 from dishes where slug = 'kung-pao-chicken'
union all select id, '大火滑炒鸡丁，加入辣椒花椒和葱段，倒入碗汁后拌入花生。', 2 from dishes where slug = 'kung-pao-chicken'
union all select id, '五花肉焯水后切成方块，肉皮朝下略煎。', 0 from dishes where slug = 'dongpo-pork'
union all select id, '砂锅铺葱姜，放入肉块并加入黄酒、酱油与冰糖。', 1 from dishes where slug = 'dongpo-pork'
union all select id, '小火焖约九十分钟，中途翻面，最后收至汤汁浓亮。', 2 from dishes where slug = 'dongpo-pork'
union all select id, '面粉分次加水揉成光滑面团，盖好醒面三十分钟。', 0 from dishes where slug = 'handmade-jiaozi'
union all select id, '白菜杀水后与肉馅、葱姜水和调味料充分搅拌。', 1 from dishes where slug = 'handmade-jiaozi'
union all select id, '擀皮包馅，水开后下锅，点两次凉水并煮至全部浮起。', 2 from dishes where slug = 'handmade-jiaozi'
union all select id, '西兰花切小朵并用淡盐水浸泡，蒜切末。', 0 from dishes where slug = 'garlic-broccoli'
union all select id, '沸水加少量盐和油，西兰花焯四十秒后沥干。', 1 from dishes where slug = 'garlic-broccoli'
union all select id, '热锅炒香蒜末，加入西兰花大火翻炒，用盐调味。', 2 from dishes where slug = 'garlic-broccoli'
union all select id, '里脊切块腌制，裹淀粉后炸至金黄酥脆。', 0 from dishes where slug = 'sweet-sour-pork'
union all select id, '青红椒与菠萝切块，快速翻炒后盛出。', 1 from dishes where slug = 'sweet-sour-pork'
union all select id, '锅中熬浓酸甜汁，倒入肉块、彩椒和菠萝快速裹匀。', 2 from dishes where slug = 'sweet-sour-pork';
